version: 0.2

phases:
  build:
    commands:
      - echo "Preparing output directory..."
      - mkdir -p output
      - cp index.html output/
      - echo "Zipping output files..."
      - zip -r output.zip output/

artifacts:
  files:
    - output.zip
