version: 0.2

phases:
  build:
    commands:
      - echo "Preparing output directory... (edited for SNS test)"
      - mkdir -p output
      - cp index.html output/
      - echo "Zipping output files..."
      - zip -r output.zip output/
# このコメントはSNS通知のテスト用です
artifacts:
  files:
    - output.zip
  post_build:
    commands:
      - echo "Deploying CloudFormation template..."
      - aws cloudformation deploy \
          --template-file main.yml \
          --stack-name my-cicd-dev \
          --parameter-overrides \
              GitHubToken=$GITHUB_TOKEN \
              GitHubOwner=yamashitakvit \
              GitHubRepo=mygitproject \
              GitHubBranch=main \
              EnvironmentType=dev \
          --capabilities CAPABILITY_NAMED_IAM
